### ISSUE TITLE
Extremely high latency within particular parts of the world

### ISSUE THREAD

**Issue by thejbone** [xJon/Hexxit-II#127]
**Basic details**
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**:  no
- **Crash/latest log link (if applicable)**: No log

**Describe the issue**

I host Chillax MC, which Hexxit II, used to be our more popular modpack, although recently there has been an ongoing issue where the overworld world is constantly causing the user's latency/ping to increase to the thousands. They can go to a different chunk/area of the map and sometimes it'll go back to normal. 

If the user accesses the spawn world (different dimension) or any other dimension than world world, their latency is perfectly fine. 

This has been an ongoing issue over the time hosting this modpack, but it was never this bad. I've reset the map before thinking that was the cause, but considering it came back it is an inevitable issue. 

From my understanding, this is an issue on the client side due to the client sending too many netty requests to the server, causing extremely slow response time / high latency.

**Comment by xJon** [comment]
Frankly, I don't have enough experience with public modded servers in order to properly help with this. The thing I do know is that there are other public servers for Hexxit II which are working well - maybe you could consider contacting any of them for advice? One server admin I know is `Rach#0018` over Discord. who runs the PewDiePie community Hexxit II server.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested!
