### ISSUE TITLE
Stuck in dimensional door

### ISSUE THREAD

**Issue by Zerenei** [xJon/Hexxit-II#136]
**Basic details**
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**

(In single player world) Not sure if this is technically considered a bug but I entered a dimensional door I found in the overworld, hit a lever inside, which triggered tnt that blew up both exit doors, and I now have no way of escaping. Commands like /kill don't work, even in a single player world it says I don't have permission to use this command, same with gamemodes. The ancient fabric does nothing and surrounds the whole place. Do I need to make another singleplayer world and restart? And just make sure not to enter these doors again?

**Comment by xJon** [comment]
First of all, apologies for the late reply! I hope you are not stuck there still.
It's the first time I hear about such issue, so I assume it's a pretty rare - as for how to get out, I'd recommend using the command `/cofh tpx` in order to teleport between dimensions.
This seems like a bug to be reported to the mod authors, but unfortunately it is no longer in active development for 1.12.2 so there's not much we can do.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested
