### ISSUE TITLE
No or inconsistent bat spawning 

### ISSUE THREAD

**Issue by KynLeg** [xJon/Hexxit-II#162]
I noticed that bats and squids are not spawning at all 
I tested everything

**Comment by xJon** [comment]
I'm unable to reproduce the squid spawn on a singleplayer world, do you have more steps for reproduction?
![image](https://user-images.githubusercontent.com/8945347/180169178-a5a1bd13-6a24-4f7c-9bc6-2f52ff7982e5.png)
Regarding bats, I am having more trouble, the spawn weights might be a bit off because there are a lot of ambient fireflies spawning instead, so I'll take note of that, thanks!

**Comment by xJon** [comment]
Unless someone magically fixes Mo' Creatures' Custom Mob Spawner, this will probably not be fixable unfortunately. Thank you nonetheless for the report!

**Comment by xJon** [comment]
Will be fixed in the next update due to the removal of CustomMobSpawner with [Mo' Creatures Extended](https://www.curseforge.com/minecraft/mc-mods/mo-creatures-extended) :)

**Comment by xJon** [comment]
Fixed in update `1.5.0` thanks to the removal of Custom Mob Spawner!
