### ISSUE TITLE
Permanently losing Items when logging on LAN

### ISSUE THREAD

**Issue by Trodd3n** [xJon/Hexxit-II#173]
**Basic details**
- **Are you using Java 8, 64-bit?**:  yes
- **Did you add any additional mods**:  no
- **Crash/latest log link (if applicable)**: na

**Describe the issue**
When I connect to my roommate's lan server and play for a while then get off for a while I will spawn near spawn with nothing from my previous play session in my inventory it almost seems as if the game thinks I have two accounts (which in don't) but I can't see my last death from the note thing or if I do find my gravestone it says my player name on it but it's locked. throughout plays these last couple of days it just switches from 2 different play sessions. I can also see that my map still has the same data on it when this happens.

**Comment by xJon** [comment]
Can you send the game log of the person who is hosting the game? You can use https://mclo.gs/

**Comment by Trodd3n** [comment]
https://mclo.gs/3SnHfaj

this is the latest log from when my buddy logged on a couple of hours ago and I didn't so I don't know if the latest one will have the issue lmk if you need an older one

**Comment by xJon** [comment]
It doesn't seem too good. Can you experiment with setting a dedicated server and seeing if you still have issues? Just download from (here)[https://servers.technicpack.net/Technic/servers/hexxit-2/Hexxit-II_Server_v1.4.0.zip] and run. In order to login locally you need to input the host computer's local IP address and server port (e.g. `192.168.1.1:25565`).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested!
